package com.example.salefaster;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.salefaster.SanPham;

import com.example.salefaster.SanPhamDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sanPhamDaoConfig;

    private final SanPhamDao sanPhamDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sanPhamDaoConfig = daoConfigMap.get(SanPhamDao.class).clone();
        sanPhamDaoConfig.initIdentityScope(type);

        sanPhamDao = new SanPhamDao(sanPhamDaoConfig, this);

        registerDao(SanPham.class, sanPhamDao);
    }
    
    public void clear() {
        sanPhamDaoConfig.getIdentityScope().clear();
    }

    public SanPhamDao getSanPhamDao() {
        return sanPhamDao;
    }

}
