package com.example.salefaster;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SAN_PHAM.
 */
public class SanPham {

    private Long id;
    private String TenSP;
    private Float GiaMua;
    private Float GiaBan;
    private String Barcode;
    private Integer SoLuong;
    private java.util.Date DateCreate;
    private java.util.Date DateUpdate;

    public SanPham() {
    }

    public SanPham(Long id) {
        this.id = id;
    }

    public SanPham(Long id, String TenSP, Float GiaMua, Float GiaBan, String Barcode, Integer SoLuong, java.util.Date DateCreate, java.util.Date DateUpdate) {
        this.id = id;
        this.TenSP = TenSP;
        this.GiaMua = GiaMua;
        this.GiaBan = GiaBan;
        this.Barcode = Barcode;
        this.SoLuong = SoLuong;
        this.DateCreate = DateCreate;
        this.DateUpdate = DateUpdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTenSP() {
        return TenSP;
    }

    public void setTenSP(String TenSP) {
        this.TenSP = TenSP;
    }

    public Float getGiaMua() {
        return GiaMua;
    }

    public void setGiaMua(Float GiaMua) {
        this.GiaMua = GiaMua;
    }

    public Float getGiaBan() {
        return GiaBan;
    }

    public void setGiaBan(Float GiaBan) {
        this.GiaBan = GiaBan;
    }

    public String getBarcode() {
        return Barcode;
    }

    public void setBarcode(String Barcode) {
        this.Barcode = Barcode;
    }

    public Integer getSoLuong() {
        return SoLuong;
    }

    public void setSoLuong(Integer SoLuong) {
        this.SoLuong = SoLuong;
    }

    public java.util.Date getDateCreate() {
        return DateCreate;
    }

    public void setDateCreate(java.util.Date DateCreate) {
        this.DateCreate = DateCreate;
    }

    public java.util.Date getDateUpdate() {
        return DateUpdate;
    }

    public void setDateUpdate(java.util.Date DateUpdate) {
        this.DateUpdate = DateUpdate;
    }

}
